### ISSUE TITLE
Skriv ett gruppkontrakt

### ISSUE THREAD

**Issue by PaulineGostasson** [PaulineGostasson/hangman-projekt#1]

**Comment by erikkjell-1** [comment]
Varje grupp skall upprätta ett gruppkonktrakt med följande punkter:

- Vilka dagar och tider jobbar vi?
- Vardagar 9-16 vid hemma så är man aktiv och kommunicerar mellan 9-16. Vid arbete efter 16 så kan man publicera i Discord för att alla får se.
- Var träffas vi? Exempel: i skolan, online, på caféer m.m.
- Skolan till en början, på plats vid behov.
- Utöver Github projects ( se nedan ) Vilka kommunikationskanaler ska vi ha? Exempel: Slack, Discord, e-post...
- Discord kanal
- Vad förväntas av varje gruppmedlem gällande kommunikation?
- Aktiv under arbetsdagen via Discord.
- Vad förväntas av varje gruppmedlem gällande aktivitet?
- Att alla bidrar med sitt och är aktiva. Våga göra fel.
- Vad blir det för konsekvenser om man inte är aktiv i projektet?
- Påminna samt vid sjukdom göra så mycket man är kapabel till.

**Comment by erikkjell-1** [comment]
**### _Erik Kjell_**

**Comment by PaulineGostasson** [comment]
o/ Pauline Göstasson

**Comment by DennisByberg** [comment]
_Dennis Byberg_
